version: "3.8"

services:
  app:
    build: .
    ports:
      - "8257:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - ./next-app:/next-app
    env_file:
      - .env
    command: sh -c "npm run build && npm run start"
