import type { Metadata } from 'next';
import BaseThemeProvider from '@themes/BaseTheme';
import Header from '@components/Header';
import Footer from '@components/Footer';
import { Suspense } from 'react';
import { tCatchcopy, tContentImg1, tLink } from '@ctypes/index';
import { tCompany, tContactFormItem } from '@ctypes/map';
import { CommonDataProvider } from '@contexts/Common';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <CommonDataProvider
            domain={domain}
            contactFormItems={contactFormItems}
            menus={pages}
            catchcopy={catchcopy}
            contents={contents}
            sns={snsLinks}
          >
            <BaseThemeProvider>
              <Header sns={snsLinks} menus={menuLinks} />
              <main>{children}</main>
              <Footer />
            </BaseThemeProvider>
          </CommonDataProvider>
        </Suspense>
      </body>
    </html>
  );
}

// Contextで読み込む予定の仮データ
const domain: tCompany = {
  number: '1234567890',
  domain: 'example.com',
  organization_name: 'My Awesome Website',
  ceo_name: 'John Doe',
  ceo_post_name: 'CEO',
  tell: '012-3456-7890',
  fax: '012-3456-7890',
  postal_code: '123-4567',
  address: 'Tokyo',
  address_other: 'Shibuya',
  email: '',
  google_map: '',
  google_map_link: '',
  google_tm_script: '',
  google_tm_script_body: '',
  caption: 'Explore the amazing content on my website.',
};

const snsLinks: tLink[] = [
  {
    name: 'Facebook',
    url: 'https://line.com',
    icon: {
      url: 'ttnou/tmp/logo_facebook_white.png',
      file: 'logo_facebook_white.png',
      name: 'facebook',
      caption: 'facebook',
      uuid: 'jsladjlsadsfd',
    },
  },
  {
    name: 'Instagram',
    url: 'https://www.instagram.com',
    icon: {
      url: '/img/sns/logo_instagram_white.png',
      file: 'logo_instagram_white.png',
      name: 'instagram',
      caption: 'Instagram',
      uuid: 'dhsalfjdlskajfld;',
    },
  },
];

const menuLinks: tLink[] = [
  { name: 'Line', url: 'https://line.com', icon: null },
  {
    name: 'Instagram',
    url: 'https://www.instagram.com',
    icon: null,
  },
];

export const contents: tContentImg1[] = [
  {
    uuid: 'highlight1',
    title: '',
    catchcopy: 'Service',
    description:
      '担当ディレクター・デイナーが一貫してサポート。当社にいわゆる「営業マン」はいません。ディレクター・デザイナー・システムエンジニアが直接やりとりを行うため、客様のイメージや考えをしっかりと共有でき、スピーディでスムーズな進行を叶えます。',
    tags: [],
    img1: {
      url: '/tmp/tranp.gif',
      name: 'service visual',
      caption: '',
      file: 'tranp.gif',
      uuid: 'service-visual',
    },
    img2: null,
    label: '詳しく見る',
    href: '/service',
  },
  {
    uuid: 'highlight2',
    title: 'addonemにできること',
    catchcopy: 'ABILITY',
    description:
      '<li>デザイン</li><li>システム開発</li><li>マーケティング</li>',
    tags: [],
    img1: {
      url: '/tmp/all_ability.png',
      name: 'ability',
      caption: '',
      file: 'ability.jpg',
      uuid: 'ability',
    },
    img2: null,
    label: '実績はこちら',
    href: '/ability',
  },
];

export const pages: tLink[] = [
  { name: 'Home', url: '/', icon: null },
  { name: 'Service', url: '/service', icon: null },
  { name: 'Ability', url: '/ability', icon: null },
  { name: 'Contact', url: '/contact', icon: null },
];

export const contactFormItems: tContactFormItem[] = [
  {
    label: '会社・店名',
    name: 'company',
    type: 'text',
    required: true,
    placeholder: '',
  },
  {
    label: '名前',
    name: 'name',
    type: 'text',
    required: true,
    placeholder: '',
  },
  {
    label: '電話番号',
    name: 'tell',
    type: 'text',
    required: false,
    placeholder: '',
  },
  {
    label: 'メールアドレス',
    name: 'email',
    type: 'email',
    required: true,
    placeholder: 'Your Email',
  },
  {
    label: '住所',
    name: 'address',
    type: 'text',
    required: true,
    placeholder: '',
  },
  {
    label: '本文',
    name: 'message',
    type: 'textarea',
    required: true,
    placeholder: 'Your Message',
    row: 4,
  },
];

export const catchcopy: tCatchcopy = {
  title: 'addition onemeter',
  description: '必要と去れるものを追加し、繋げる',
  image: {
    url: '/tmp/catchcopy.svg',
    name: 'addition',
    caption: '',
    file: 'addition.jpg',
    uuid: 'addition',
  },
  tags: ['追加する', '手の届く', '繋げる'],
};
